'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace GridReportPrint


	''' <summary>
	''' _Default class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' AccessDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AccessDataSource1 As Global.System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' Grid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Grid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' btnPrint control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnPrint As Global.DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton

		''' <summary>
		''' Viewer control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Viewer As Global.DevExpress.XtraReports.Web.ReportViewer

		''' <summary>
		''' visibleIndex control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected visibleIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

		''' <summary>
		''' isPrint control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected isPrint As Global.System.Web.UI.HtmlControls.HtmlInputHidden
	End Class
End Namespace
